feat: add license check

diff --git a/.github/workflows/terraform-repo-governance.yml b/.github/workflows/terraform-repo-governance.yml
--- a/.github/workflows/terraform-repo-governance.yml
+++ b/.github/workflows/terraform-repo-governance.yml
@@ -45,6 +45,22 @@ jobs:
       matrix:
         repo: ${{ fromJson(needs.getrepos.outputs.repoarray) }}
     steps:
-      - name: Test
+      - name: License check (SNFR10)
+        id: snfr10
         run: |
-          echo ${{ matrix.repo }}
+          ISMITLICENSE=$(gh api graphql -f query='query {
+            repository(owner: "azure", name: "'${{ matrix.repo }}'") {
+              licenseInfo {
+                name
+              }
+            }
+          }' | jq -e '.data.repository.licenseInfo.name == "MIT License"')
+          if [ "$ISMITLICENSE" = "true" ]; then
+            echo "MIT License found"
+            exit 1
+          else
+            echo "MIT License not found"
+            gh issue create --title "MIT License not found" --body "The repository ${{ matrix.repo }} does not have a MIT License"
+          fi
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
